--CREATE TYPE status AS ENUM (
--    'OPENED', 'ACTIVE', 'CLOSED', 'FROZEN', 'ARRESTED'
--);

-- Acount
CREATE TABLE account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    balance DOUBLE PRECISION,
    interest_rate DOUBLE PRECISION,
    is_recalc BOOLEAN,
    card_exist BOOLEAN,
    status VARCHAR(50)
);

--Card
CREATE TABLE card (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    card_id VARCHAR(100) NOT NULL,
    payment_system VARCHAR(50),
    status VARCHAR(50),
    CONSTRAINT fk_card_account FOREIGN KEY (account_id)
        REFERENCES account (id)
);

--CREATE TYPE type AS ENUM (
--    'DEPOSIT',
--    'WITHDRAW'
--);

-- Payment
CREATE TABLE payment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    payment_date DATE,
    amount DOUBLE PRECISION,
    is_credit BOOLEAN,
    payed_at TIMESTAMP,
    type VARCHAR(50),
    CONSTRAINT fk_payment_account FOREIGN KEY (account_id)
        REFERENCES account (id)
);

--CREATE TYPE transaction_status AS ENUM (
--    'ALLOWED',
--    'PROCESSING',
--    'COMPLETE',
--    'BLOCKED',
--    'CANCELLED'
--);

-- Transactions
CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    card_id BIGINT,
    type VARCHAR(50),
    amount DOUBLE PRECISION,
    status VARCHAR(50),
    timestamp TIMESTAMP,
    CONSTRAINT fk_transaction_account FOREIGN KEY (account_id)
        REFERENCES account (id),
    CONSTRAINT fk_transaction_card FOREIGN KEY (card_id)
        REFERENCES card (id)
);
