spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/creditdb
    username: client_user
    password: client_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
server:
  port: 8082
credit:
  limit: 2000000
